import { z } from "zod";

export const jobDetailsSchema = z.object({
  jobNumber: z.string().min(1, "Fill up this field"),
  recruitmentCode: z.string().min(1, "Fill up this field"),
  projectHeading: z.string().min(1, "Fill up this field"),
  companyNumber: z.string().min(1, "Fill up this field"),
  companyName: z.string().min(1, "Fill up this field"),
  specialConditions: z.string().min(0).optional(),
  employmentStatus: z.string().min(1, "Fill up this field"),
  industry: z.string().min(1, "Fill up this field"),
  occupationClassification: z.string().min(1, "Fill up this field"),
  jobType: z.string().min(1, "Fill up this field"),
  salaryRange: z.string().min(1, "Fill up this field"),
  salaryDetails: z.string().min(1, "Fill up this field"),
  benefitsDetails: z.string().min(0).optional(),
  point: z.string().min(0).optional(),
  jobDescription: z.string().min(1, "Fill up this field"),
  qualificationName: z.string().min(1, "Fill up this field"),
  workLocation: z.string().min(1, "Fill up this field"),
  municipalityHokkaido: z.string().min(0).optional(),
  municipalityAomori: z.string().min(0).optional(),
  municipalityIwate: z.string().min(0).optional(),
  municipalityAkita: z.string().min(0).optional(),
  municipalityMiyagi: z.string().min(0).optional(),
  municipalityFukushima: z.string().min(0).optional(),
  municipalityYamagata: z.string().min(0).optional(),
  municipalityTochigi: z.string().min(0).optional(),
  municipalityNagano: z.string().min(0).optional(),
  transportationAccessInformation: z.string().min(1, "Fill up this field"),
  workingDays: z.string().min(1, "Fill up this field"),
  earlyWorkingHours: z.string().min(0).optional(),
  dayWorkingHours: z.string().min(0).optional(),
  lateworkingHours: z.string().min(0).optional(),
  nightworkingHours: z.string().min(0).optional(),
  firstOtherWorkingHours: z.string().min(0).optional(),
  secondOtherWorkingHours: z.string().min(0).optional(),
  holidaysOrVacations: z.string().min(0).optional(),
  personInCharge: z.string().min(1, "Fill up this field"),
  hpUpdateDate: z.string().min(1, "Fill up this field"),
  webListing: z.string().min(0).optional(),
  jobRegistrationDate: z.string().min(1, "Fill up this field"),
  registeredDate: z.string().min(1, "Fill up this field"),
  updateDateAndTime: z.string().min(1, "Fill up this field"),
  inCharge: z.string().min(0).optional(),
  recruitmentCaseManager: z.string().min(1, "Fill up this field"),
  directlyPostedOnIndeed: z.string().min(0).optional(),
  recruitmentBoxDirectPosting: z.string().min(0).optional(),
  talentClipPublicOrPrivate: z.string().min(0).optional(),
  nurseHpPublicOrPrivate: z.string().min(0).optional(),
  status: z.string().min(1, "Fill up this field"),
  memo: z.string().min(0).optional(),
  secondMemo: z.string().min(0).optional(),
  webMediaDisclosureOrNonDisclosure: z.string().min(0).optional(),
});
